spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_resident?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  thymeleaf:
    cache: false